<?xml version="1.0" encoding="ISO-8859-1"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="PrimitiveTypes">
    <eClassifiers xsi:type="ecore:EDataType" name="Boolean"/>
    <eClassifiers xsi:type="ecore:EDataType" name="String"/>
  </ecore:EPackage>
  <ecore:EPackage name="AM3">
    <eClassifiers xsi:type="ecore:EClass" name="Megamodel">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="megamodelElements" ordered="false" upperBound="-1" eType="/1/MegamodelElement" containment="true" eOpposite="/1/MegamodelElement/megamodel"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MegamodelElement" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="megamodel" ordered="false" lowerBound="1" eType="/1/Megamodel" eOpposite="/1/Megamodel/megamodelElements"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Artifact" abstract="true" eSuperTypes="/1/MegamodelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="uri" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="domains" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="authors" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="see" ordered="false" unique="false" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationEnds" ordered="false" upperBound="-1" eType="/1/RelationEnd" eOpposite="/1/RelationEnd/artifact"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Model" eSuperTypes="/1/Artifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="Metamodel" eSuperTypes="/1/Model"/>
    <eClassifiers xsi:type="ecore:EClass" name="ATLFile" abstract="true" eSuperTypes="/1/Artifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="ATLTransformation" eSuperTypes="/1/ATLFile"/>
    <eClassifiers xsi:type="ecore:EClass" name="ATLLib" eSuperTypes="/1/ATLFile"/>
    <eClassifiers xsi:type="ecore:EClass" name="ATLQuery" eSuperTypes="/1/ATLFile"/>
    <eClassifiers xsi:type="ecore:EClass" name="TCS" eSuperTypes="/1/Artifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="Projector" abstract="true" eSuperTypes="/1/Artifact"/>
    <eClassifiers xsi:type="ecore:EClass" name="Injector" abstract="true" eSuperTypes="/1/Projector"/>
    <eClassifiers xsi:type="ecore:EClass" name="XMLInjector" eSuperTypes="/1/Injector"/>
    <eClassifiers xsi:type="ecore:EClass" name="EBNFInjector" eSuperTypes="/1/Injector">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="classNamePrefix" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Extractor" abstract="true" eSuperTypes="/1/Projector">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="extension" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramMetamodel" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="paramModel" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ATLExtractor" eSuperTypes="/1/Extractor"/>
    <eClassifiers xsi:type="ecore:EClass" name="EBNFExtractor" eSuperTypes="/1/Extractor"/>
    <eClassifiers xsi:type="ecore:EClass" name="XMLExtractor" eSuperTypes="/1/Extractor"/>
    <eClassifiers xsi:type="ecore:EClass" name="RelationEnd" eSuperTypes="/1/MegamodelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="artifact" ordered="false" lowerBound="1" eType="/1/Artifact" eOpposite="/1/Artifact/relationEnds"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="relation" ordered="false" lowerBound="1" eType="/1/Relation" eOpposite="/1/Relation/relationEnds"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Relation" abstract="true" eSuperTypes="/1/MegamodelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="relationEnds" ordered="false" upperBound="-1" eType="/1/RelationEnd" eOpposite="/1/RelationEnd/relation"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ATLTransformationParameter" abstract="true" eSuperTypes="/1/Relation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterName" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InputMetamodelOfTransformation" eSuperTypes="/1/ATLTransformationParameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="OutputMetamodelOfTransformation" eSuperTypes="/1/ATLTransformationParameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="LibOfTransformation" eSuperTypes="/1/ATLTransformationParameter"/>
    <eClassifiers xsi:type="ecore:EClass" name="ConformedToMetamodel" eSuperTypes="/1/Relation"/>
    <eClassifiers xsi:type="ecore:EClass" name="RepresentationOf" eSuperTypes="/1/Relation"/>
    <eClassifiers xsi:type="ecore:EClass" name="DocumentationOf" eSuperTypes="/1/Relation"/>
    <eClassifiers xsi:type="ecore:EClass" name="ProjectorParameter" abstract="true" eSuperTypes="/1/Relation"/>
    <eClassifiers xsi:type="ecore:EClass" name="MetamodelOfProjectedFile" eSuperTypes="/1/ProjectorParameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="metamodelName" ordered="false" unique="false" lowerBound="1" eType="/0/String"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
